#!/usr/bin/env python
import sys
sys.path.append('/Users/aaron/Dropbox/PhD/Advance_Elective/Python_Programming_For_Research/Greengraph')

import greengraph
from greengraph.command import process
process()
